#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Rebuild kb/_index/{aliases.json,by_status.md,graph.md} from every concept's node.yaml.

Generated files only — never hand-edit them; rerun this instead.

Usage:
    kb_reindex.py
"""
import json
import os

import _bootstrap  # noqa: F401
import okf


def main():
    slugs = okf.list_concepts()
    nodes = {slug: okf.load_node(slug) for slug in slugs}

    aliases = {}
    for slug, node in nodes.items():
        aliases[slug] = slug
        for a in node.get("aliases", []):
            aliases[a] = slug
    os.makedirs(okf.INDEX_DIR, exist_ok=True)
    with open(os.path.join(okf.INDEX_DIR, "aliases.json"), "w", encoding="utf-8") as f:
        json.dump(aliases, f, ensure_ascii=False, indent=2, sort_keys=True)
        f.write("\n")

    by_status_lines = ["# Concepts by status", "", "> Generated by kb_reindex.py — do not hand-edit.", ""]
    for status in okf.STATUSES:
        matching = sorted(s for s, n in nodes.items() if n.get("status") == status)
        by_status_lines.append(f"## {status} ({len(matching)})")
        for s in matching:
            by_status_lines.append(f"- `{s}` — {nodes[s].get('title', '')} (v{nodes[s]['current_version']})")
        by_status_lines.append("")
    with open(os.path.join(okf.INDEX_DIR, "by_status.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(by_status_lines))

    graph_lines = ["# Concept graph (related + version chain)", "",
                   "> Generated by kb_reindex.py — do not hand-edit.", ""]
    for slug, node in sorted(nodes.items()):
        graph_lines.append(f"## `{slug}` ({node.get('status')})")
        related = node.get("related", [])
        if related:
            graph_lines.append("- related: " + ", ".join(f"`{r}`" for r in related))
        chain = []
        for v in okf.list_versions(slug):
            meta, _ = okf.load_version(slug, v)
            chain.append(f"v{v}({meta.get('status')})")
        graph_lines.append("- version chain: " + " -> ".join(chain))
        graph_lines.append("")
    with open(os.path.join(okf.INDEX_DIR, "graph.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(graph_lines))

    print(f"reindexed {len(slugs)} concept(s) -> kb/_index/{{aliases.json,by_status.md,graph.md}}")


if __name__ == "__main__":
    main()
