"""
BullDvg Boost — Paper-trade tracker.

Runs daily after market close. Records:
  - Today's BullDvg fire detection + filter pass
  - Boost window status (active / inactive, sessions remaining)
  - VNI close (proxy for boost return realization)
  - Cumulative ghost-NAV: hypothetical alpha from boost = sum over active
    sessions of lift × VNI_return (lift=0.25, matching production config)

Modes:
  --update     append today's row (default — for scheduled task)
  --report     print summary report (call manually or via 12mo scheduled task)
  --backfill   reconstruct log from BQ history (one-time bootstrap)

Output:
  bull_div_boost_log.csv        — append-only daily decisions (from bull_div_boost.py)
  bull_div_boost_tracker.csv    — daily NAV/alpha tracking
  bull_div_boost_report.txt     — generated by --report
"""
import argparse
import subprocess
import sys
from datetime import datetime, date, timedelta
from pathlib import Path

import pandas as pd

WORKDIR = Path(__file__).parent
TRACKER_PATH = WORKDIR / 'bull_div_boost_tracker.csv'
REPORT_PATH = WORKDIR / 'bull_div_boost_report.txt'
DEPLOY_DATE = date(2026, 5, 19)
REPORT_DATE = date(2027, 5, 19)  # 12 months after deploy

LIFT = 0.25  # matches production max_pos 12->15 (+25% capacity)


def _bq(sql):
    res = subprocess.run(['bq','query','--use_legacy_sql=false',
                          '--project_id=lithe-record-440915-m9',
                          '--format=csv','--max_rows=20000','-q',sql],
                         capture_output=True, text=True, shell=True)
    if res.returncode != 0:
        raise RuntimeError(res.stderr)
    return res.stdout


def get_latest_vni():
    """Latest VNI Close + 252d high."""
    sql = ('WITH t AS (SELECT t.time, t.Close, t.High FROM tav2_bq.ticker AS t '
           'WHERE t.ticker="VNINDEX" AND t.time >= DATE_SUB(CURRENT_DATE(), INTERVAL 365 DAY)), '
           'latest AS (SELECT * FROM t WHERE time=(SELECT MAX(time) FROM t)), '
           'hi AS (SELECT MAX(High) AS hi252 FROM t) '
           'SELECT l.time, l.Close, h.hi252 FROM latest l, hi h')
    out = _bq(sql).strip().split('\n')
    if len(out) < 2: return None
    cols = out[0].split(','); row = out[1].split(',')
    return dict(zip(cols, row))


def cmd_update():
    """Append today's tracking row."""
    # Run detection + state update via bull_div_boost module
    from bull_div_boost import detect_today, update_state, log_decision
    info = detect_today()
    decision = update_state(info)
    log_decision(info, decision)

    # Append tracker row with VNI close (for alpha attribution)
    today = info['date']
    cl = float(info.get('close_hi252', 0)) if info.get('close_hi252') else None
    vni = get_latest_vni()
    vni_close = float(vni['Close']) if vni else None

    # Compute daily VNI return (if we have previous row)
    vni_ret = None
    cum_alpha = 0.0
    if TRACKER_PATH.exists():
        prev = pd.read_csv(TRACKER_PATH)
        if not prev.empty and vni_close:
            prev_close = prev.iloc[-1].get('vni_close')
            if prev_close and not pd.isna(prev_close):
                vni_ret = vni_close / float(prev_close) - 1
            cum_alpha = float(prev.iloc[-1].get('cum_alpha_pct', 0))

    # If boost active and we have VNI return, accumulate alpha
    if decision['boost_active'] and vni_ret is not None:
        cum_alpha += LIFT * vni_ret * 100

    row = {
        'date': today,
        'vni_close': vni_close,
        'close_hi252': info.get('close_hi252'),
        'bull_fire': int(info.get('any_bull_fire', False)),
        'filter_pass': int(info.get('filter_pass', False)),
        'boost_active': int(decision['boost_active']),
        'max_positions': decision['max_positions'],
        'fire_date_anchor': (decision.get('window_end') or ''),
        'vni_ret_d': f"{vni_ret:.5f}" if vni_ret is not None else '',
        'cum_alpha_pct': f"{cum_alpha:.4f}",
        'reason': decision['reason'],
    }
    write_header = not TRACKER_PATH.exists()
    with TRACKER_PATH.open('a', encoding='utf-8') as f:
        if write_header:
            f.write(','.join(row.keys()) + '\n')
        f.write(','.join(str(v) for v in row.values()) + '\n')
    print(f"[{today}] boost={'YES' if decision['boost_active'] else 'no'}  "
          f"max_pos={decision['max_positions']}  "
          f"close_hi252={cl if cl else 'n/a'}  "
          f"cum_alpha={cum_alpha:+.3f}%  ({decision['reason']})")


def cmd_report():
    """Generate 12-month report."""
    if not TRACKER_PATH.exists():
        print("No tracker data yet."); return
    df = pd.read_csv(TRACKER_PATH, parse_dates=['date'])
    df = df.sort_values('date').reset_index(drop=True)

    fires = df[df['filter_pass']==1]
    boosts = df[df['boost_active']==1]
    n_days = len(df)
    n_boost_days = len(boosts)
    boost_pct = n_boost_days/n_days*100 if n_days else 0
    cum_alpha = df['cum_alpha_pct'].iloc[-1] if not df.empty else 0

    deploy_d = pd.Timestamp(DEPLOY_DATE)
    today = pd.Timestamp(date.today())
    months_elapsed = (today.year - deploy_d.year)*12 + (today.month - deploy_d.month)

    txt = []
    txt.append("="*72)
    txt.append("BullDvg Boost — Paper-Trade Report")
    txt.append("="*72)
    txt.append(f"Deploy date: {DEPLOY_DATE}")
    txt.append(f"Report date: {date.today()}  ({months_elapsed} months elapsed)")
    txt.append(f"Tracking window: {df['date'].iloc[0].date()} -> {df['date'].iloc[-1].date()}")
    txt.append(f"Total sessions tracked: {n_days}")
    txt.append(f"Boost-active sessions: {n_boost_days}  ({boost_pct:.1f}%)")
    txt.append(f"Filtered BullDvg fires: {len(fires)}")
    txt.append("")
    txt.append(f"Cumulative alpha (lift={LIFT}, additive on VNI ret during boost window):")
    txt.append(f"  {cum_alpha:+.3f}%  (paper-trade estimate)")
    txt.append("")
    txt.append("Fire log:")
    if fires.empty:
        txt.append("  (none — no filtered BullDvg fires during tracking)")
    else:
        for _, r in fires.iterrows():
            ch = r['close_hi252']
            ch_s = f"{float(ch):.3f}" if ch and not pd.isna(ch) else 'n/a'
            txt.append(f"  {r['date'].date()}  close_hi252={ch_s}  reason={r['reason']}")
    txt.append("")

    # Validate vs backtest expectation
    if months_elapsed >= 11:
        # 12 months expected alpha range from backtest: +0.5 to +1.3pp
        txt.append("Validation vs backtest expectation (OOS 2019-2026):")
        txt.append(f"  Expected 12mo alpha range: +0.5pp to +1.3pp")
        txt.append(f"  Realized 12mo alpha:       {cum_alpha:+.3f}pp")
        if cum_alpha >= 0.5:
            verdict = "🟢 GREEN — confirmed live alpha within backtest range"
        elif cum_alpha >= 0:
            verdict = "🟡 YELLOW — below backtest range but positive"
        else:
            verdict = "🔴 RED — negative alpha; revert max_positions to 12 in recommend_holistic.py"
        txt.append(f"  Verdict: {verdict}")
        txt.append("")
        txt.append("Decision rule:")
        txt.append("  GREEN  -> keep deployment, optionally bump lift to 35% (next OOS test)")
        txt.append("  YELLOW -> extend tracking 6 more months before action")
        txt.append("  RED    -> revert: edit recommend_holistic.py to hard-code max_positions=12")
    else:
        txt.append(f"Report incomplete: only {months_elapsed} months elapsed; ")
        txt.append(f"  wait until {REPORT_DATE} for final verdict.")
    txt.append("")
    txt.append("Decision audit log: bull_div_boost_log.csv")
    txt.append("Daily NAV tracker:  bull_div_boost_tracker.csv")

    out = '\n'.join(txt)
    print(out)
    REPORT_PATH.write_text(out, encoding='utf-8')
    print(f"\nReport saved: {REPORT_PATH}")


def cmd_backfill():
    """One-time: reconstruct historical fire events from BQ to seed the tracker."""
    print("Backfill not implemented — start fresh from deploy date.")
    print("Daily --update calls will accumulate the log going forward.")


if __name__ == '__main__':
    p = argparse.ArgumentParser()
    p.add_argument('mode', nargs='?', default='update',
                   choices=['update','report','backfill'])
    args = p.parse_args()
    {'update': cmd_update, 'report': cmd_report, 'backfill': cmd_backfill}[args.mode]()
