#!/bin/bash
# BA-system v11 — Automated Linux server deployment
#
# Usage:
#   1. Upload all code files to server (~/ba-system/)
#   2. Upload sa-key.json to ~/.config/gcloud/sa-key.json
#   3. Run: chmod +x deploy_linux.sh && ./deploy_linux.sh
#
# Prerequisites (sudo done OUTSIDE script):
#   sudo apt update && sudo apt install -y python3.11 python3.11-venv python3-pip git curl
#   curl https://sdk.cloud.google.com | bash  # install gcloud
#   exec -l $SHELL  # reload PATH

set -e  # exit on first error

INSTALL_DIR="${HOME}/ba-system"
SA_KEY="${HOME}/.config/gcloud/sa-key.json"
PROJECT_ID="lithe-record-440915-m9"

echo "=================================================================="
echo "  BA-system v11 — Linux server deployment"
echo "=================================================================="
echo

# ─── 1. Verify prerequisites ──────────────────────────────────────
echo "[1/8] Verifying prerequisites…"

command -v python3.11 >/dev/null 2>&1 || { echo "ERROR: python3.11 not found"; exit 1; }
command -v bq >/dev/null 2>&1 || { echo "ERROR: bq (Google Cloud SDK) not found"; exit 1; }
command -v crontab >/dev/null 2>&1 || { echo "ERROR: cron not found. apt install cron"; exit 1; }

if [ ! -f "$SA_KEY" ]; then
    echo "ERROR: Service account key not found at $SA_KEY"
    echo "  Upload your sa-key.json there first."
    exit 1
fi

if [ ! -d "$INSTALL_DIR" ]; then
    echo "ERROR: Code not at $INSTALL_DIR — upload code first."
    exit 1
fi

echo "  ✓ Python 3.11, bq CLI, cron, sa-key, code dir — all present"

# ─── 2. Set Vietnam timezone ──────────────────────────────────────
echo "[2/8] Setting timezone to Asia/Ho_Chi_Minh…"
if [ "$(timedatectl show -p Timezone --value 2>/dev/null)" != "Asia/Ho_Chi_Minh" ]; then
    sudo timedatectl set-timezone Asia/Ho_Chi_Minh
    echo "  ✓ Timezone set"
else
    echo "  ✓ Timezone already correct"
fi

# ─── 3. Create Python venv + install deps ─────────────────────────
echo "[3/8] Setting up Python virtual environment…"
cd "$INSTALL_DIR"
if [ ! -d "venv" ]; then
    python3.11 -m venv venv
    echo "  ✓ venv created"
else
    echo "  ✓ venv already exists"
fi

source venv/bin/activate
pip install --quiet --upgrade pip
pip install --quiet -r requirements.txt
echo "  ✓ Dependencies installed"

# ─── 4. Google Cloud auth ─────────────────────────────────────────
echo "[4/8] Authenticating with Google Cloud…"
chmod 600 "$SA_KEY"
gcloud auth activate-service-account --key-file="$SA_KEY" --quiet
gcloud config set project "$PROJECT_ID" --quiet
echo "  ✓ gcloud configured for $PROJECT_ID"

# Test BQ access
TEST_RESULT=$(bq query --use_legacy_sql=false --format=csv --quiet \
    'SELECT 1 AS test_value LIMIT 1' 2>&1 | tail -1)
if echo "$TEST_RESULT" | grep -q "test_value\|^1$"; then
    echo "  ✓ BQ access verified"
else
    echo "  ⚠ BQ test inconclusive — check manually: bq query 'SELECT 1'"
fi

# ─── 5. Path adjustments in code ──────────────────────────────────
echo "[5/8] Updating code paths for Linux…"

# Backup originals
cp recommend_holistic.py recommend_holistic.py.bak.$(date +%s) 2>/dev/null || true
cp telegram_recommend.py telegram_recommend.py.bak.$(date +%s) 2>/dev/null || true

# Replace Windows paths with Linux equivalents in scripts that use them
for f in *.py; do
    if grep -l 'r"C:\\Users\\hotro\\OneDrive\\Pictures\\Documents\\WorkingClaude"' "$f" >/dev/null 2>&1; then
        sed -i 's|r"C:\\\\Users\\\\hotro\\\\OneDrive\\\\Pictures\\\\Documents\\\\WorkingClaude"|"'"$INSTALL_DIR"'"|g' "$f"
        echo "  ✓ Updated WORKDIR in $f"
    fi
done

# Replace bq.cmd with bq for Linux
for f in *.py; do
    if grep -l 'bq.cmd' "$f" >/dev/null 2>&1; then
        sed -i 's|r"C:\\\\Users\\\\hotro\\\\AppData\\\\Local\\\\Google\\\\Cloud SDK\\\\google-cloud-sdk\\\\bin\\\\bq.cmd"|"bq"|g' "$f"
        echo "  ✓ Updated BQ_BIN in $f"
    fi
done

# ─── 6. Configure Telegram ────────────────────────────────────────
echo "[6/8] Telegram config check…"
if [ ! -f telegram_config.json ]; then
    if [ -f telegram_config.template.json ]; then
        cp telegram_config.template.json telegram_config.json
        chmod 600 telegram_config.json
        echo "  ⚠ Created telegram_config.json from template."
        echo "  ⚠ EDIT IT with your real bot_token + chat_id BEFORE proceeding!"
        echo "    nano telegram_config.json"
        echo
        read -p "Press ENTER after editing the config, or Ctrl-C to abort..."
    else
        echo "  ERROR: No telegram_config.template.json found"
        exit 1
    fi
else
    chmod 600 telegram_config.json
    echo "  ✓ telegram_config.json exists (chmod 600)"
fi

# ─── 7. Create daily run wrapper ──────────────────────────────────
echo "[7/8] Creating telegram_run_daily.sh wrapper…"
cat > "$INSTALL_DIR/telegram_run_daily.sh" << EOF
#!/bin/bash
# Auto-generated by deploy_linux.sh — daily BA-system Telegram trigger

cd "$INSTALL_DIR"
source venv/bin/activate
export GOOGLE_APPLICATION_CREDENTIALS="$SA_KEY"

LOGFILE="telegram_run_\$(date +%Y-%m-%d).log"

echo "===== BA-system Telegram run started \$(date) =====" >> "\$LOGFILE"
python telegram_recommend.py >> "\$LOGFILE" 2>&1
EXITCODE=\$?
echo "===== Exit code: \$EXITCODE at \$(date) =====" >> "\$LOGFILE"

# Cleanup logs >30 days
find . -name 'telegram_run_*.log' -mtime +30 -delete

exit \$EXITCODE
EOF
chmod +x "$INSTALL_DIR/telegram_run_daily.sh"
echo "  ✓ telegram_run_daily.sh created"

# ─── 8. Register cron entry ───────────────────────────────────────
echo "[8/8] Registering cron entry (Mon-Fri 18:00)…"
CRON_LINE="0 18 * * 1-5 $INSTALL_DIR/telegram_run_daily.sh"

# Check if already in crontab
if crontab -l 2>/dev/null | grep -F "$INSTALL_DIR/telegram_run_daily.sh" >/dev/null; then
    echo "  ✓ Cron entry already exists"
else
    (crontab -l 2>/dev/null; echo "$CRON_LINE") | crontab -
    echo "  ✓ Cron entry added: $CRON_LINE"
fi

echo
echo "=================================================================="
echo "  ✅ Deployment complete!"
echo "=================================================================="
echo
echo "Next steps:"
echo
echo "1. Test the live engine end-to-end:"
echo "   cd $INSTALL_DIR && source venv/bin/activate"
echo "   python recommend_holistic.py"
echo
echo "2. Test Telegram dry-run:"
echo "   python telegram_recommend.py --dry-run"
echo
echo "3. Test real Telegram send:"
echo "   python telegram_recommend.py"
echo
echo "4. Verify cron will trigger Monday-Friday at 18:00 (Vietnam time)"
echo "   crontab -l"
echo
echo "5. Tomorrow ~18:00, check log:"
echo "   tail -50 $INSTALL_DIR/telegram_run_\$(date +%Y-%m-%d).log"
echo
echo "6. Run validation backtest (~10-15 min, optional):"
echo "   python test_state_var_with_p3.py"
echo
echo "7. Set up monitoring (manual):"
echo "   - Schedule a daily check of latest log file"
echo "   - Alert on 'Exit code: 0' missing"
echo
