# BA-system v11 - Automated Windows server deployment
#
# Usage:
#   1. Upload all code files to deployment dir
#   2. Upload sa-key.json to %USERPROFILE%\.config\gcloud\sa-key.json
#   3. Run as Administrator (recommended for Task Scheduler):
#      powershell -ExecutionPolicy Bypass -File deploy_windows.ps1

$ErrorActionPreference = 'Stop'

$InstallDir = "$env:USERPROFILE\ba-system"  # adjust if needed
$SaKey      = "$env:USERPROFILE\.config\gcloud\sa-key.json"
$ProjectId  = "lithe-record-440915-m9"

Write-Host "=================================================================="
Write-Host "  BA-system v11 - Windows server deployment"
Write-Host "=================================================================="
Write-Host ""

# 1. Verify prerequisites
Write-Host "[1/7] Verifying prerequisites..."

$pyOk = $false
foreach ($cmd in @('python', 'python3', 'py')) {
    $ver = (& $cmd --version 2>&1 | Out-String).Trim()
    if ($ver -match '3\.1[1-9]') { $pyOk = $true; $PyCmd = $cmd; break }
}
if (-not $pyOk) {
    Write-Host "ERROR: Python 3.11+ not found. Install from python.org" -ForegroundColor Red
    exit 1
}

$bqOk = $null
try { $bqOk = (Get-Command bq.cmd -ErrorAction Stop) } catch {
    try { $bqOk = (Get-Command bq -ErrorAction Stop) } catch {}
}
if (-not $bqOk) {
    Write-Host "ERROR: Google Cloud SDK (bq) not found. Install from cloud.google.com/sdk" -ForegroundColor Red
    exit 1
}

if (-not (Test-Path $SaKey)) {
    Write-Host "ERROR: Service account key not at $SaKey" -ForegroundColor Red
    exit 1
}

if (-not (Test-Path $InstallDir)) {
    Write-Host "ERROR: Code not at $InstallDir" -ForegroundColor Red
    exit 1
}

Write-Host "  OK Python 3.11+, bq CLI, sa-key, code dir - all present" -ForegroundColor Green

# 2. Python venv + deps
Write-Host "[2/7] Setting up Python virtual environment..."
Set-Location $InstallDir
if (-not (Test-Path "venv")) {
    & $PyCmd -m venv venv
    Write-Host "  OK venv created"
}

# Use venv pip
$VenvPip = "$InstallDir\venv\Scripts\pip.exe"
$VenvPy  = "$InstallDir\venv\Scripts\python.exe"
& $VenvPip install --quiet --upgrade pip
& $VenvPip install --quiet -r requirements.txt
Write-Host "  OK Dependencies installed" -ForegroundColor Green

# 3. Google Cloud auth
Write-Host "[3/7] Authenticating with Google Cloud..."
& gcloud auth activate-service-account --key-file=$SaKey --quiet
& gcloud config set project $ProjectId --quiet
Write-Host "  OK gcloud configured for $ProjectId" -ForegroundColor Green

# Test BQ
$TestResult = & bq query --use_legacy_sql=false --format=csv --quiet 'SELECT 1 AS test_value' 2>&1
if ($TestResult -match '1') {
    Write-Host "  OK BQ access verified" -ForegroundColor Green
} else {
    Write-Host "  WARN BQ test inconclusive" -ForegroundColor Yellow
}

# 4. Telegram config
Write-Host "[4/7] Telegram config check..."
$TelConfig = "$InstallDir\telegram_config.json"
if (-not (Test-Path $TelConfig)) {
    if (Test-Path "$InstallDir\telegram_config.template.json") {
        Copy-Item "$InstallDir\telegram_config.template.json" $TelConfig
        Write-Host "  Created telegram_config.json from template." -ForegroundColor Yellow
        Write-Host "  EDIT IT with real bot_token + chat_id BEFORE proceeding:" -ForegroundColor Yellow
        Write-Host "    notepad $TelConfig"
        Write-Host ""
        Read-Host "Press ENTER after editing config, or Ctrl-C to abort"
    } else {
        Write-Host "  ERROR: telegram_config.template.json missing" -ForegroundColor Red
        exit 1
    }
} else {
    Write-Host "  OK telegram_config.json exists"
}

# 5. Create wrapper batch file
Write-Host "[5/7] Creating telegram_run_daily.bat..."
$BatPath = "$InstallDir\telegram_run_daily.bat"
@"
@echo off
REM Auto-generated by deploy_windows.ps1 - daily BA-system Telegram trigger

cd /d $InstallDir

set LOGFILE=telegram_run_%date:~10,4%-%date:~4,2%-%date:~7,2%.log

echo ===== BA-system Telegram run started %date% %time% ===== >> %LOGFILE%

$VenvPy telegram_recommend.py >> %LOGFILE% 2>&1
set EXITCODE=%ERRORLEVEL%
echo ===== Exit code: %EXITCODE% at %time% ===== >> %LOGFILE%

REM Cleanup logs older than 30 days
forfiles /p . /m telegram_run_*.log /d -30 /c "cmd /c del @path" 2>nul

exit /b %EXITCODE%
"@ | Set-Content -Encoding ASCII $BatPath

Write-Host "  OK $BatPath created" -ForegroundColor Green

# 6. Register Task Scheduler entry
Write-Host "[6/7] Registering Windows Task Scheduler entry..."

$TaskName = "BA-System Telegram Daily 1800"

$existing = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
if ($existing) {
    Write-Host "  Found existing task - unregistering first..." -ForegroundColor Yellow
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:`$false
}

$Trigger = New-ScheduledTaskTrigger -Weekly -DaysOfWeek Monday, Tuesday, Wednesday, Thursday, Friday -At 18:00
$Action = New-ScheduledTaskAction -Execute $BatPath -WorkingDirectory $InstallDir
$Settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
    -WakeToRun -StartWhenAvailable `
    -RestartCount 5 -RestartInterval (New-TimeSpan -Minutes 5) `
    -ExecutionTimeLimit (New-TimeSpan -Minutes 30)

Register-ScheduledTask -TaskName $TaskName -Trigger $Trigger -Action $Action `
    -Settings $Settings `
    -Description "BA-system v11 daily Telegram notifier - Mon-Fri 18:00 VN time" `
    -User $env:USERNAME | Out-Null

Write-Host "  OK Task registered: $TaskName" -ForegroundColor Green

# 7. Enable wake timers
Write-Host "[7/7] Enabling wake-from-sleep..."
powercfg /setacvalueindex SCHEME_CURRENT SUB_SLEEP bd3b718a-0680-4d9d-8ab2-e1d2b4ac806d 1 2>$null
powercfg /setdcvalueindex SCHEME_CURRENT SUB_SLEEP bd3b718a-0680-4d9d-8ab2-e1d2b4ac806d 1 2>$null
powercfg /setactive SCHEME_CURRENT 2>$null
Write-Host "  OK Wake timers enabled (AC + DC)"

Write-Host ""
Write-Host "=================================================================="
Write-Host "  Deployment complete!" -ForegroundColor Green
Write-Host "=================================================================="
Write-Host ""
Write-Host "Next steps:"
Write-Host ""
Write-Host "1. Test the live engine:"
Write-Host "   cd $InstallDir"
Write-Host "   .\venv\Scripts\python.exe recommend_holistic.py"
Write-Host ""
Write-Host "2. Test Telegram dry-run:"
Write-Host "   .\venv\Scripts\python.exe telegram_recommend.py --dry-run"
Write-Host ""
Write-Host "3. Test real send:"
Write-Host "   .\venv\Scripts\python.exe telegram_recommend.py"
Write-Host ""
Write-Host "4. Trigger scheduled task manually:"
Write-Host "   Start-ScheduledTask -TaskName '$TaskName'"
Write-Host ""
Write-Host "5. Check task status:"
Write-Host "   Get-ScheduledTaskInfo -TaskName '$TaskName'"
Write-Host ""
