#!/usr/bin/env python3
"""
oil_sector_sensitivity.py — Brent crude sensitivity across the VN oil & gas chain
=================================================================================
Two dimensions the user asked for:
  (1) PROFIT impact   — quarterly NP/NPM/GPM/Revenue vs Brent quarterly avg
                        (level, lagged level, and YoY-change correlations)
  (2) PRICE impact    — monthly stock return regressed on monthly Brent return
                        (oil beta, R^2) + return-volatility amplification

Universe grouped by ICB chain position (thuong nguon -> ha nguon):
  UPSTREAM/SERVICES (573)  PVD PVS PVB PVC
  REFINE/DISTRIB    (533)  BSR PLX OIL
  GAS DISTRIB      (7573)  GAS PGS CNG PGD PGC PVG
  FERT/CHEM        (1357)  DPM DCM DGC CSV
  TRANSPORT        (2773)  PVT VIP VTO GSP PVP
Output: data/oil_sector_sensitivity.md
"""
import warnings; warnings.filterwarnings("ignore")
import sys
try: sys.stdout.reconfigure(encoding="utf-8")
except Exception: pass
import os, subprocess, tempfile
from io import StringIO
import numpy as np, pandas as pd

WORKDIR=r"/home/trido/thanhdt/WorkingClaude"
PROJECT="lithe-record-440915-m9"
BQ_BIN=r"bq"

GROUPS=[
 ("UPSTREAM / OILFIELD SVC (573)", ["PVD","PVS","PVB","PVC"]),
 ("REFINE / DISTRIBUTION (533)",   ["BSR","PLX","OIL"]),
 ("GAS DISTRIBUTION (7573)",       ["GAS","PGS","CNG","PGD","PGC","PVG"]),
 ("FERTILIZER / CHEM (1357)",      ["DPM","DCM","DGC","CSV"]),
 ("MARINE TRANSPORT (2773)",       ["PVT","VIP","VTO","GSP","PVP"]),
]
ALL=[t for _,g in GROUPS for t in g]

def bq(sql):
    with tempfile.NamedTemporaryFile(mode="w",suffix=".sql",delete=False,encoding="utf-8") as f:
        f.write(sql); tmp=f.name
    try:
        r=subprocess.run(f'type "{tmp}" | "{BQ_BIN}" query --use_legacy_sql=false '
                         f'--project_id={PROJECT} --format=csv --max_rows=5000000',
                         capture_output=True,text=True,timeout=600,shell=True)
    finally:
        try: os.unlink(tmp)
        except: pass
    if r.returncode!=0 or not r.stdout.strip():
        raise RuntimeError(r.stderr[:500])
    return pd.read_csv(StringIO(r.stdout.strip()))

def ols_beta(y,x):
    """return beta, alpha, r2, n for y ~ a + b*x"""
    m=np.isfinite(y)&np.isfinite(x); y=y[m]; x=x[m]; n=len(y)
    if n<12: return (np.nan,np.nan,np.nan,n)
    b,a=np.polyfit(x,y,1)
    yhat=a+b*x; ss=np.sum((y-yhat)**2); st=np.sum((y-y.mean())**2)
    r2=1-ss/st if st>0 else np.nan
    return (b,a,r2,n)

def main():
    lines=[]; P=lambda s="":(print(s),lines.append(s))
    tks="','".join(ALL)

    # ---- Brent monthly ----
    br=pd.read_csv(os.path.join(WORKDIR,"data","brent_monthly_full.csv"))
    br["month"]=pd.PeriodIndex(br["month"],freq="M")
    br=br.set_index("month").sort_index()
    br["bret"]=br["brent"].pct_change()
    # quarterly avg brent for profit analysis
    brq=br["brent"].groupby(br.index.asfreq("Q")).mean().rename("brent_q").to_frame()
    brq["brent_q_yoy"]=brq["brent_q"].pct_change(4)
    brq["d_brent_q"]=brq["brent_q"].pct_change()

    # ================= PRICE: monthly stock return vs Brent return =================
    px=bq(f"""
      WITH m AS (
        SELECT t.ticker, DATE_TRUNC(t.time, MONTH) AS mo, t.time, t.Close,
          ROW_NUMBER() OVER (PARTITION BY t.ticker, DATE_TRUNC(t.time,MONTH)
                             ORDER BY t.time DESC) AS rn
        FROM tav2_bq.ticker AS t
        WHERE t.ticker IN ('{tks}') AND t.Close IS NOT NULL )
      SELECT ticker, mo, Close FROM m WHERE rn=1 ORDER BY ticker, mo""")
    px["month"]=pd.PeriodIndex(pd.to_datetime(px["mo"]),freq="M")
    px=px.sort_values(["ticker","month"])
    px["sret"]=px.groupby("ticker")["Close"].pct_change()
    px=px.merge(br[["bret"]].reset_index(),on="month",how="left")
    px["bret_lag"]=px.groupby("ticker")["bret"].shift(0)  # placeholder
    # lagged brent: stock reacts to prior-month oil move
    blag=br[["bret"]].copy(); blag.index=blag.index+1; blag=blag.rename(columns={"bret":"bret_l1"})
    px=px.merge(blag.reset_index(),on="month",how="left")

    P("# Anh huong cua gia dau Brent len nhom xang dau VN (chuoi thuong->ha nguon)")
    P(f"_Brent monthly 2013-2026 (latest {br.index[-1]} = ${br['brent'].iloc[-1]:.0f}); "
      f"stock monthly returns from tav2_bq.ticker. Generated by oil_sector_sensitivity.py_")
    P("")
    P("## PHAN 1 — Anh huong len GIA co phieu (oil beta)")
    P("Hoi quy: stock_monthly_return ~ a + beta * Brent_monthly_return")
    P("beta = % co phieu di chuyen khi dau +1%. R2 = % bien dong gia giai thich boi dau.")
    P("beta_l1 = phan ung voi cu dau THANG TRUOC (do tre).")
    P("")
    price_rows=[]
    for gname,gtk in GROUPS:
        P(f"### {gname}")
        P(f"{'tk':<5}{'n_mo':>5}{'beta':>8}{'tstat~':>8}{'R2':>7}{'beta_l1':>9}{'corr':>7}{'ann_vol%':>9}")
        for tk in gtk:
            d=px[px["ticker"]==tk]
            if len(d)<18: continue
            b,a,r2,n=ols_beta(d["sret"].values,d["bret"].values)
            bl,_,r2l,nl=ols_beta(d["sret"].values,d["bret_l1"].values)
            cc=d[["sret","bret"]].corr().iloc[0,1]
            vol=d["sret"].std()*np.sqrt(12)*100
            # rough t-stat of beta via corr
            tval=cc*np.sqrt(max(n-2,1))/np.sqrt(max(1-cc*cc,1e-9))
            P(f"{tk:<5}{n:>5}{b:>8.2f}{tval:>8.1f}{r2:>7.2f}{bl:>9.2f}{cc:>7.2f}{vol:>9.0f}")
            price_rows.append((gname,tk,n,b,r2,bl,cc,vol))
        # group aggregate beta (equal-weight avg monthly return)
        g=px[px["ticker"].isin(gtk)].groupby("month").agg(sret=("sret","mean"),bret=("bret","first"),
                                                          bret_l1=("bret_l1","first")).reset_index()
        b,a,r2,n=ols_beta(g["sret"].values,g["bret"].values)
        bl,_,_,_=ols_beta(g["sret"].values,g["bret_l1"].values)
        P(f"{'>>EW':<5}{n:>5}{b:>8.2f}{'':>8}{r2:>7.2f}{bl:>9.2f}")
        P("")

    # ================= PROFIT: quarterly fundamentals vs Brent =================
    fin=bq(f"""
      SELECT t.ticker, t.time, t.quarter, t.NP_P0, t.Revenue_P0, t.NPM_P0, t.GPM_P0, t.NP_R
      FROM tav2_bq.ticker_financial AS t
      WHERE t.ticker IN ('{tks}') ORDER BY t.ticker, t.time""")
    fin["time"]=pd.to_datetime(fin["time"])
    fin["q"]=pd.PeriodIndex(fin["time"],freq="Q")
    fin=fin.merge(brq.reset_index().rename(columns={"month":"q"}),on="q",how="left")
    # lagged brent (profit reacts to prior oil, esp upstream)
    brq_l1=brq.copy(); brq_l1.index=brq_l1.index+1
    fin=fin.merge(brq_l1[["brent_q"]].rename(columns={"brent_q":"brent_q_l1"}).reset_index().rename(columns={"month":"q"}),on="q",how="left")
    brq_l2=brq.copy(); brq_l2.index=brq_l2.index+2
    fin=fin.merge(brq_l2[["brent_q"]].rename(columns={"brent_q":"brent_q_l2"}).reset_index().rename(columns={"month":"q"}),on="q",how="left")

    P("## PHAN 2 — Anh huong len LOI NHUAN (quarterly)")
    P("corr cua tung chi tieu voi Brent. NP=net profit (level), NPM=net margin, GPM=gross margin.")
    P("c_lvl = corr(metric, Brent_quy hien tai); c_l1/l2 = voi Brent tre 1/2 quy (do tre vong von/ton kho);")
    P("c_dNP = corr(NP YoY-ratio NP_R, Brent YoY) — bat hieu ung GIA dau TANG/GIAM (inventory).")
    P("")
    prof_rows=[]
    for gname,gtk in GROUPS:
        P(f"### {gname}")
        P(f"{'tk':<5}{'nQ':>4}{'NP~lvl':>8}{'NP~l1':>7}{'NP~l2':>7}{'NPM~lvl':>9}{'GPM~lvl':>9}{'dNP~dOil':>9}")
        for tk in gtk:
            d=fin[fin["ticker"]==tk].dropna(subset=["brent_q"])
            d=d[d["NP_P0"].notna()]
            if len(d)<8: continue
            def c(x,y):
                m=d[[x,y]].dropna()
                if len(m)<8: return np.nan
                return m[x].corr(m[y])
            np_lvl=c("NP_P0","brent_q"); np_l1=c("NP_P0","brent_q_l1"); np_l2=c("NP_P0","brent_q_l2")
            npm=c("NPM_P0","brent_q"); gpm=c("GPM_P0","brent_q")
            dnp=c("NP_R","brent_q_yoy")
            f=lambda v:f"{v:>+.2f}" if np.isfinite(v) else "   .  "
            P(f"{tk:<5}{len(d):>4}{f(np_lvl):>8}{f(np_l1):>7}{f(np_l2):>7}{f(npm):>9}{f(gpm):>9}{f(dnp):>9}")
            prof_rows.append((gname,tk,np_lvl,np_l1,np_l2,npm,gpm,dnp))
        P("")

    # ================= SUMMARY: best lag & sign by group =================
    P("## TONG HOP — dau hieu & do tre theo vi tri chuoi")
    pr=pd.DataFrame(price_rows,columns=["grp","tk","n","beta","r2","beta_l1","corr","vol"])
    pf=pd.DataFrame(prof_rows,columns=["grp","tk","np_lvl","np_l1","np_l2","npm","gpm","dnp"])
    P(f"{'group':<32}{'oil_beta':>9}{'R2':>6}{'vol%':>7}{'NP~lvl':>8}{'NP~l1':>7}{'NP~l2':>7}{'dNP~dOil':>9}")
    for gname,_ in GROUPS:
        a=pr[pr["grp"]==gname]; b=pf[pf["grp"]==gname]
        if len(a)==0: continue
        P(f"{gname:<32}{a['beta'].median():>9.2f}{a['r2'].median():>6.2f}{a['vol'].median():>7.0f}"
          f"{b['np_lvl'].median():>+8.2f}{b['np_l1'].median():>+7.2f}{b['np_l2'].median():>+7.2f}{b['dnp'].median():>+9.2f}")
    P("")
    P("Doc: oil_beta cao = gia co phieu nhay voi dau; NP~l1/l2 > NP~lvl = loi nhuan phan ung TRE;")
    P("dNP~dOil duong manh = loi nhuan an theo HUONG gia dau (inventory/crack), thuong la refine/distrib.")

    out=os.path.join(WORKDIR,"data","oil_sector_sensitivity.md")
    with open(out,"w",encoding="utf-8") as f: f.write("\n".join(lines))
    # also persist raw tables
    pr.to_csv(os.path.join(WORKDIR,"data","oil_price_beta.csv"),index=False)
    pf.to_csv(os.path.join(WORKDIR,"data","oil_profit_corr.csv"),index=False)
    P(f"\nSaved {out}")

if __name__=="__main__": main()
