#!/usr/bin/env python3
"""
recommend_lh.py
===============
Live LH-system picks: top FA-LH A+B tier names from latest available quarter,
filtered by CRISIS gate (skip when state=1).

Usage:
  python recommend_lh.py              # uses latest data
  python recommend_lh.py 2026-05-14   # snapshot at specific date

Output:
  - `lh_picks_<date>.csv` — ranked top picks for next quarterly cohort buy
  - Console summary with state-gate verdict

Inputs:
  - fa_ratings_lh.csv (generated by score_fa_lh.py)
  - vnindex_5state.csv
  - tav2_bq.ticker_1m for fresh liquidity / price snapshot
"""
import warnings; warnings.filterwarnings("ignore")
import sys, os, subprocess, tempfile
try: sys.stdout.reconfigure(encoding="utf-8")
except Exception: pass
from io import StringIO
import pandas as pd, numpy as np

PROJECT = "lithe-record-440915-m9"
BQ_BIN = r"bq"
TARGET_POSITIONS = 10           # total target portfolio size
HOLD_QUARTERS = 4               # 1Y hold per position
TIERS = ("A", "B")              # eligible tiers

def bq_query(sql):
    with tempfile.NamedTemporaryFile(mode="w", suffix=".sql", delete=False, encoding="utf-8") as f:
        f.write(sql); tmp = f.name
    try:
        cmd = f'type "{tmp}" | "{BQ_BIN}" query --use_legacy_sql=false --project_id={PROJECT} --format=csv --max_rows=100000'
        r = subprocess.run(cmd, capture_output=True, text=True, timeout=600, shell=True)
    finally:
        try: os.unlink(tmp)
        except: pass
    if r.returncode != 0: raise RuntimeError(f"{r.stderr[:500]}")
    return pd.read_csv(StringIO(r.stdout.strip()))

snap_dt = pd.Timestamp(sys.argv[1]) if len(sys.argv) > 1 else pd.Timestamp.today().normalize()
print(f"LH picks @ {snap_dt.date()}")

# 1) Load ratings
ratings = pd.read_csv("fa_ratings_lh.csv", parse_dates=["time", "Release_Date"])
latest_q = ratings.sort_values("quarter").iloc[-1]["quarter"]
print(f"Latest quarter in fa_ratings_lh: {latest_q}")

# 2) Check CRISIS gate (today's state)
state_df = pd.read_csv("vnindex_5state.csv", parse_dates=["time"]).sort_values("time")
recent_state = state_df[state_df["time"] <= snap_dt].iloc[-1]
print(f"Current 5-state regime: state={recent_state['state']} (1=CRISIS, 2=BEAR, 3=NEU, 4=BULL, 5=EX-BULL) @ {recent_state['time'].date()}")
if recent_state["state"] == 1:
    print("\n🔴 CRISIS GATE FIRED — skip new buys today. Existing positions hold until expiry.")
    print("   Re-run when state transitions out of CRISIS (state ≥ 2).")
    sys.exit(0)
else:
    print(f"  Gate OK — proceed with picks.\n")

# 3) Pull fresh live snapshot from ticker (most recent available row per ticker)
live = bq_query(f"""
WITH latest AS (
  SELECT t1.ticker AS tk, MAX(t1.time) AS time FROM tav2_bq.ticker_1m AS t1
  WHERE t1.time <= "{snap_dt.date()}" AND t1.time >= DATE_SUB("{snap_dt.date()}", INTERVAL 90 DAY)
  GROUP BY t1.ticker
)
SELECT t.ticker, t.time, t.Close, t.Volume_3M_P50,
       t.Volume_3M_P50 * t.Close AS liq_vnd
FROM tav2_bq.ticker_1m AS t
JOIN latest AS l ON l.tk = t.ticker AND l.time = t.time
WHERE t.Close > 0 AND t.Volume_3M_P50 IS NOT NULL
""")
print(f"  Live universe: {len(live)} tickers")

# 4) Filter latest-Q ratings to A+B with liquidity ≥ 1B/day
latest_picks = ratings[(ratings["quarter"] == latest_q) & (ratings["tier"].isin(TIERS))].copy()
print(f"  A+B picks for {latest_q}: {len(latest_picks)}")
latest_picks = latest_picks.merge(live[["ticker", "Close", "liq_vnd"]], on="ticker", how="inner",
                                    suffixes=("_q", "_now"))
print(f"  Joined with live data: {len(latest_picks)}")
latest_picks = latest_picks[latest_picks["liq_vnd"] >= 1e9]
print(f"  Post liquidity filter (≥1B VND/day): {len(latest_picks)}")

# 5) Sort by score desc, take top N (more than target, allow operator to choose)
top_picks = latest_picks.sort_values("score", ascending=False).head(TARGET_POSITIONS * 2)

# 6) Output
out = top_picks[["ticker", "quarter", "sub", "ICB_Code", "tier", "score", "pct",
                 "Close_q", "Close_now", "liq_vnd", "Release_Date"]].copy()
out["Close_change"] = (out["Close_now"] / out["Close_q"] - 1).round(4)
out["liq_bil"] = (out["liq_vnd"] / 1e9).round(2)
out["score"] = out["score"].round(3)
out["pct"] = out["pct"].round(3)
out = out.drop(columns=["liq_vnd", "Close_q", "Close_now"])
out.to_csv(f"lh_picks_{snap_dt.date()}.csv", index=False)

print("\n" + "="*100)
print(f"TOP {TARGET_POSITIONS} LH PICKS — buy {TARGET_POSITIONS // HOLD_QUARTERS}-{TARGET_POSITIONS // HOLD_QUARTERS + 1} this rebal, hold 1Y")
print("="*100)
print(out.head(TARGET_POSITIONS).to_string(index=False))
print(f"\nFull top {len(out)} written to lh_picks_{snap_dt.date()}.csv")
print(f"Buy approx {TARGET_POSITIONS // HOLD_QUARTERS}-{TARGET_POSITIONS // HOLD_QUARTERS + 1} new this quarter (staggered cohort) — pick from rows where ticker NOT in current portfolio")
