-- DDL DE XUAT cho `tav2_mike.treasury_share_events` (CHUA CHAY — cho Mike/user duyet).
-- Sinh boi: build_treasury_share_events.py (one-time, 577 dong).
-- KHONG partition: 577 dong / ~500 ngay khac nhau => partition DAY se tao ~500 phan vung 1 dong.
-- Cluster theo ticker: moi consumer deu loc theo ticker (oshares_live, backtest PIT).
CREATE TABLE `lithe-record-440915-m9.tav2_mike.treasury_share_events` (
  id                    STRING  NOT NULL OPTIONS(description="TRSY-sha1(ticker|public_date|action_type)[:16]. Deterministic cho CHINH cot id. CANH BAO: dieu do KHONG lam MERGE an toan — MOI lan nap lai BAT BUOC la rebuild toan bo bang (CREATE OR REPLACE / truncate+load), TUYET DOI khong MERGE per-row. Ly do: cot dedup (dup_group_id/is_canonical/duplicate_of) chi dung trong pham vi MOT lan build — mark_duplicates() chi nhin cac dong cua lan chay hien tai, khong doc lai bang da co. Dong moi MERGE vao se mang is_canonical=TRUE mac dinh, dung canh dong cu cung is_canonical=TRUE => tai dien bug dem-2-lan, khong co loi nao bao."),
  ticker                STRING  NOT NULL,
  public_date           DATE    NOT NULL OPTIONS(description="Ngay cong bo ket qua giao dich (treasury_news.public_date). KHONG phai ngay so lieu biet duoc — xem confirmed_asof."),
  action_type           STRING  NOT NULL OPTIONS(description="buy_done | sell_done"),
  outstanding_delta     INT64            OPTIONS(description="Delta luong CP LUU HANH (= -treasury_news.shares_delta). buy_done AM (mua vao quy => luu hanh giam), sell_done DUONG. NULL khi size_status='UNSIZED' — TUYET DOI khong doc NULL thanh 0."),
  size_status           STRING  NOT NULL OPTIONS(description="SIZED | UNSIZED"),
  source                STRING           OPTIONS(description="VENDOR_PUBLISHED | SIBLING_ROW | OSHARES_DELTA_INFERRED. NULL khi UNSIZED. BA TIER KHONG DUOC TRON: xem confidence."),
  confidence            STRING           OPTIONS(description="high (VENDOR_PUBLISHED, SIBLING_ROW — deu la so vendor cong bo) | medium (OSHARES_DELTA_INFERRED — suy tu lech OShares, control n=13: 77% khop chinh xac, 85% sai<=5%) | NULL (UNSIZED)"),
  confirmed_asof        DATE             OPTIONS(description="CHI cho OSHARES_DELTA_INFERRED: ngay som nhat con so nay THUC SU biet duoc = MAX(time, Release_Date) cua dong ticker_financial quy SAU. Join PIT phai dung cot nay, KHONG phai public_date. NULL cho moi tier khac."),
  unsized_reason        STRING           OPTIONS(description="Ly do khong suy duoc size (CA_CONFOUNDED / NO_MOVE / MULTI_EVENT / NO_DATA / ISSUANCE_MATCH / SIGN_MISMATCH / OVER_CAP). Chi co gia tri khi UNSIZED."),
  inferred_window_days  INT64            OPTIONS(description="CHI cho OSHARES_DELTA_INFERRED: be rong THAT SU cua cua so OShares dung de suy ra so nay. 28/33 dong ~1 quy (76-115 ngay); 5 dong phai noi ra 2 quy (176-188: TSJ 2019-01-23, SGP 2018-06-04, DRH 2020-04-06, LSS 2021-04-09, SMN 2023-06-27) vi quy ke tiep bi confounder. Nhom control do do chinh xac (77%/85%/92%) gan nhu chi gom ca 1 quy => KHONG dai dien cho 5 dong nay: tin hon thi loc inferred_window_days <= 120."),
  dup_group_id          STRING           OPTIONS(description="Nhom cac dong la CUNG MOT giao dich that (vendor dang o 2 ngay khac nhau, hoac 1 dong vendor chong 1 dong suy tu OShares). NULL khi dong nay dung mot minh. Luat: cung ticker+action_type, cach dong NEO cua nhom <=14 ngay, |outstanding_delta| lech <=5%."),
  is_canonical          BOOL    NOT NULL OPTIONS(description="TRUE cho DUNG MOT dong moi nhom trung (va moi dong dung mot minh). MOI phep tong hop outstanding_delta PHAI co WHERE is_canonical — khong loc thi 2 nhom hien tai lam SUM phong 3.008.900 CP. Canonical chon theo tier tin nhat (VENDOR_PUBLISHED > SIBLING_ROW > OSHARES_DELTA_INFERRED), roi public_date som nhat, roi id nho nhat."),
  duplicate_of          STRING           OPTIONS(description="id cua dong canonical trong cung nhom. NULL khi is_canonical=TRUE. Dong trung O LAI trong bang de audit, khong bi xoa."),
  source_news_ids       STRING           OPTIONS(description="Danh sach treasury_news.news_id da gop vao su kien nay, ngan cach dau phay."),
  first_public_datetime TIMESTAMP        OPTIONS(description="MIN(public_datetime) trong cac dong nguon."),
  loaded_at             TIMESTAMP NOT NULL,
  loader_version        STRING    NOT NULL
)
CLUSTER BY ticker
OPTIONS(description="Su kien mua/ban co phieu quy da THUC HIEN, gop tu tav2_bq.treasury_news theo (ticker, public_date, action_type). One-time load 2026-09-18. 577 su kien: 128 VENDOR_PUBLISHED + 3 SIBLING_ROW + 33 OSHARES_DELTA_INFERRED + 413 UNSIZED. UNSIZED la gioi han CUA NGUON (short_content/source/source_link NULL 100%), khong phai thieu no luc. BON CAI BAY: (1) outstanding_delta NULL != 0, KHONG COALESCE(...,0). (2) public_date KHONG phai ngay PIT cho 33 dong suy luan — dung COALESCE(confirmed_asof, public_date) <= asof. (3) ba tier khong dang tin nhu nhau, xem confidence. (4) SUM(outstanding_delta) KHONG AN TOAN neu khong loc theo cot dedup: PHAI co WHERE is_canonical, vi cung mot giao dich that co the nam o 2 dong (do duoc 2 nhom, SUM tho phong 3.008.900 CP). Dedup chi phu dong SIZED; COUNT(*) so su kien co the con phong toi da 24 cap UNSIZED nghi trung nhung khong chung minh duoc. NAP LAI: MOI lan nap lai BAT BUOC la rebuild toan bo (CREATE OR REPLACE / truncate+load), KHONG duoc MERGE per-row — cac cot dedup chi dung trong pham vi 1 lan build (mark_duplicates() khong doc lai bang da co), nen dong MERGE them se mang is_canonical=TRUE dung canh dong cu cung TRUE va lam SUM dem 2 lan trong im lang. treasury_news VAN nhan dong moi (2026-09-13, 2026-09-16) => tinh huong nay la thuc te, khong gia dinh.");
